app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    $img = Image::make(public_path().'/foo.jpg')->fit(200, 200, function ($constraint) {
        $constraint->upsize();
    },'left');
//    dd($img);

    return $img->response('jpg');
});
//
//    Route::get('/apn-notifications', [
////      'middleware' => ['notifications'],
//      'as' => 'apn-push-notifications.push',
//      'uses' => 'PushNotificationController@pushNotifications'
//    ]);

    Route::get('/add-notifications', [
//      'middleware' => ['notifications'],
      'as' => 'push-notifications.add',
      'uses' => 'FacadeControllers\PushNotificationController@addNotifications'
    ]);
    Route::get('/gcm-notifications', [
//      'middleware' =`
      'as' => 'gcm-push-notifications.push',
      'uses' => 'GCMController@pushNotifications'
    ]);

    Route::get('auth/{app}', 'Auth\AuthController@redirectToProvider');
    Route::get('auth/{app}/callback', 'Auth\AuthController@handleProviderCallback');

    #region image actions
    Route::post('image-scale-crop/preview', [
      'as' => 'image-scale-crop.preview',
      'uses' => 'ImageScaleCropController@preview'
    ]);

    Route::post('image-scale-crop/crop', [
      'as' => 'image-scale-crop.crop',
      'uses' => 'ImageScaleCropController@crop'
    ]);

    Route::get('image-size/seeder', [
      'as' => 'image-size.seeder',
      'uses' => 'ImageSizeController@seeder'
    ]);
    #endregion
    # region newsletter and contact

    Route::post('news-letter/add', [
      'as' => 'news-letter.add',
      'uses' => 'NewsLetterController@add'
    ]);
    Route::get('news-letter/export-csv', [
      'as' => 'news-letter.export-csv',
      'uses' => 'NewsLetterController@exportCSV'
    ]);
    Route::get('contact/create', [
      'as' => 'contact.create',
      'uses' => 'ContactController@create'
    ]);
    Route::post('contact/add', [
      'as' => 'contact.add',
      'uses' => 'ContactController@add'
    ]);
    #endregion

    #region geo loaction
    Route::get('geo-location/addresses', [
      'as' => 'geo-location.addresses',
      'uses' => 'GeoLocationController@getAddresses'
    ]);
    #endregion

    #region resource controllers
    Route::resource('image-scale-crop', 'ImageScaleCropController');
    Route::resource('image-size', 'ImageSizeController');
    Route::resource('geo-location', 'GeoLocationController');
    Route::resource('news-letter', 'NewsLetterController');
    #endregion

#region vuetests
    Route::resource('vue','VueController');
#endregion

app/ImageSize.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ImageSize extends Model {
  protected $fillable = ['name', 'slug', 'height', 'width', 'type'];
}

app/Http/Controllers/ImageSizeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\ImageSize;
use Illuminate\Http\Request;

use App\Http\Requests;

class ImageSizeController extends Controller
{


  public function __construct(Request $request) {
//    dd($request);


  }

  /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $image_sizes = ImageSize::all();
        return view('image_size.index' ,compact('image_sizes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model  = new ImageSize();
        return view('image_size.create',compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required'
        ]);

        if(isset($request)){
            $input = $request->all();
            // check for requsted parameters
            if(count($input)){
                $result = ImageSize::create($input);
                // if the insert is success
                if($result){
                    return redirect('image-size');
                }else{
                    return redirect()->back()->withInput();
                }


            }
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (is_numeric($id) && //validate for the record id
          !empty($id) &&
          $id != 0) {
            $model  = ImageSize::findOrFail($id);
            if(isset($model)){
                return view('image_size.edit', compact('model'));

            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (is_numeric($id) && //validate for the record id
          !empty($id) &&
          $id != 0) {
            $input = $request->all();
            $update_status  = ImageSize::find($id)->update($input);
            //redirects if the record is updated
            if($update_status){
                return redirect('image-size');
            }else{
                return redirect()->back()->withInput();
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (is_numeric($id) && //validate for the record id
          !empty($id) &&
          $id != 0) {
            $model = ImageSize::findOrFail($id);
            $delete_status  = $model->delete();
            //redirects if successfully deleted
            if($delete_status){
                return redirect('image-size');
            }else{
                return redirect()->back()->withInput();
            }
        }
    }

  public function seeder() {

    $seeder = new \MainSiteMigrationSeeder();
    $result = $seeder->run();
  }
}

resources/views/image_size/create.blade.php
{!! Form::model($model, array('route' => array('image-size.store'), 'class' => 'form-horizontal')) !!}
@include('image_size.form')
{!! Form::close() !!}

resources/views/image_size/edit.blade.php
{!! Form::model($model, array('method' => 'put',  'route' => array('image-size.update' , $model->id), 'class' => 'form-horizontal')) !!}
@include('image_size.form')
{!! Form::close() !!}

resources/views/image_size/form.blade.php
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('Name', NULL, ['class' => 'col-sm-5 control-label']) !!}
            <div class="col-sm-5">
                {!! Form::text('name', NULL ,['class' => 'form-control'])  !!}
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('Slug', NULL, ['class' => 'col-sm-5 control-label ']) !!}
            <div class="col-sm-5">
                {!! Form::text('slug', NULL ,['class' => 'form-control'])  !!}
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group" id="Assigned_contacts_form_group">
            {!! Form::label('Width', NULL, ['class' => 'col-sm-5 control-label']) !!}
            <div class="col-sm-5">
                {!! Form::text('width', NULL ,['class' => 'form-control'])  !!}
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('Height', NULL, ['class' => 'col-sm-5 control-label']) !!}
            <div class="col-sm-5">
                {!! Form::text('height', NULL ,['class' => 'form-control'])  !!}
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('Type', NULL, ['class' => 'col-sm-5 control-label ']) !!}
            <div class="col-sm-5">
                {!! Form::select('type', [
                  'Article'=>'Article',
                  'Address'=>'Address',
                  'Taxonomy'=>'Taxonomy',
                  'Agenda'=>'Agenda',
                  'BBN'=>'BBN',
                  'Folder'=>'Folder',
                  'User'=>'User',], NULL ,['class' => 'form-control chosen-select']) !!}
            </div>
        </div>
    </div>

    <div class="col-md-3">
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    </div>

</div>

resources/views/image_size/index.blade.php
<table>
    <thead>
    <tr>
        <th>Name </th>
        <th>Type </th>
        <th>Height</th>
        <th>Width</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($image_sizes as $image_size)
        <tr>

            <td>{{$image_size->name}}</td>
            <td>{{$image_size->type}}</td>
            <td>{{$image_size->height}}</td>
            <td>{{$image_size->width}}</td>
            <td><a href="{{ route('image-size.edit' , $image_size->id) }}"></a>
                <a href="{{ route('image-size.destroy' , $image_size->id) }}" class="btn btn-danger action_confirm" data-method="delete" data-token="{{ csrf_token() }}"><i class="glyphicon glyphicon-remove"></i></a></td>
        </tr>
    @endforeach
    </tbody>
</table>